import {
  Code2,
  Database,
  Network,
  Cpu,
  Server,
  Cloud,
  Terminal,
  FileCode,
  Settings,
  Zap,
  Shield,
  Globe,
  Monitor,
  Smartphone,
  Palette,
  Rocket,
  Target,
  TrendingUp,
  BarChart,
  Brain,
  Lightbulb,
  Book,
  GraduationCap,
  Users,
  Mail,
  Link,
  Award,
  Trophy,
  Flame,
  Sparkles,
  Search,
  Folder,
  File,
  Image,
  Video,
  FileText,
  Calendar,
  Clock,
  RefreshCw,
  Play,
  Camera,
  Phone,
  MessageSquare,
  Share2,
  Tag,
  Bookmark,
  Flag,
  MapPin,
  Languages,
  DollarSign,
  CreditCard,
  ShoppingCart,
  Package,
  Gift,
  Activity,
  Star,
  Heart,
  ThumbsUp,
  Medal,
  Wand2,
} from "lucide-react"
import {
  SiPython,
  SiJavascript,
  SiHtml5,
  SiReact,
  SiAngular,
  SiNodedotjs,
  SiDjango,
  SiLaravel,
  SiGit,
  SiJava,
  SiCsharp,
  SiTypescript,
  SiNextdotjs,
  SiVuedotjs,
  SiExpress,
  SiMongodb,
  SiPostgresql,
  SiMysql,
  SiRedis,
  SiDocker,
  SiKubernetes,
  SiAws,
  SiAzure,
  SiGithub,
  SiGitlab,
  SiFigma,
  SiTailwindcss,
  SiBootstrap,
  SiSass,
  SiLess,
  SiGraphql,
  SiApollographql,
  SiFirebase,
  SiSupabase,
} from "react-icons/si"

// Icon library mapping
export const iconLibrary: Record<string, React.ComponentType<{ className?: string }>> = {
  // Lucide Icons - Development & Tech
  "Code2": Code2,
  "Database": Database,
  "Network": Network,
  "Cpu": Cpu,
  "Server": Server,
  "Cloud": Cloud,
  "Terminal": Terminal,
  "FileCode": FileCode,
  "Settings": Settings,
  "Zap": Zap,
  "Shield": Shield,
  "Globe": Globe,
  "Monitor": Monitor,
  "Smartphone": Smartphone,
  "Palette": Palette,
  "Rocket": Rocket,
  "Target": Target,
  "TrendingUp": TrendingUp,
  "BarChart": BarChart,
  "Brain": Brain,
  "Lightbulb": Lightbulb,
  "Book": Book,
  "GraduationCap": GraduationCap,
  "Users": Users,
  "Mail": Mail,
  "Link": Link,
  "Award": Award,
  "Trophy": Trophy,
  "Flame": Flame,
  "Sparkles": Sparkles,
  "Search": Search,
  "Folder": Folder,
  "File": File,
  "Image": Image,
  "Video": Video,
  "FileText": FileText,
  "Calendar": Calendar,
  "Clock": Clock,
  "RefreshCw": RefreshCw,
  "Play": Play,
  "Camera": Camera,
  "Phone": Phone,
  "MessageSquare": MessageSquare,
  "Share2": Share2,
  "Tag": Tag,
  "Bookmark": Bookmark,
  "Flag": Flag,
  "MapPin": MapPin,
  "Languages": Languages,
  "DollarSign": DollarSign,
  "CreditCard": CreditCard,
  "ShoppingCart": ShoppingCart,
  "Package": Package,
  "Gift": Gift,
  "Activity": Activity,
  "Star": Star,
  "Heart": Heart,
  "ThumbsUp": ThumbsUp,
  "Medal": Medal,
  "Wand2": Wand2,
  // React Icons (Simple Icons) - Technologies
  "SiPython": SiPython,
  "SiJavascript": SiJavascript,
  "SiHtml5": SiHtml5,
  "SiReact": SiReact,
  "SiAngular": SiAngular,
  "SiNodedotjs": SiNodedotjs,
  "SiDjango": SiDjango,
  "SiLaravel": SiLaravel,
  "SiGit": SiGit,
  "SiJava": SiJava,
  "SiCsharp": SiCsharp,
  "SiTypescript": SiTypescript,
  "SiNextdotjs": SiNextdotjs,
  "SiVuedotjs": SiVuedotjs,
  "SiExpress": SiExpress,
  "SiMongodb": SiMongodb,
  "SiPostgresql": SiPostgresql,
  "SiMysql": SiMysql,
  "SiRedis": SiRedis,
  "SiDocker": SiDocker,
  "SiKubernetes": SiKubernetes,
  "SiAws": SiAws,
  "SiAzure": SiAzure,
  "SiGithub": SiGithub,
  "SiGitlab": SiGitlab,
  "SiFigma": SiFigma,
  "SiTailwindcss": SiTailwindcss,
  "SiBootstrap": SiBootstrap,
  "SiSass": SiSass,
  "SiLess": SiLess,
  "SiGraphql": SiGraphql,
  "SiApollographql": SiApollographql,
  "SiFirebase": SiFirebase,
  "SiSupabase": SiSupabase,
}

// Get icon by name
export function getIcon(iconName: string): React.ComponentType<{ className?: string }> | null {
  return iconLibrary[iconName] || null
}

// Get all available icon names
export function getAvailableIcons(): string[] {
  return Object.keys(iconLibrary)
}

// Popular/common icons for quick selection
export const popularIcons = [
  "Code2",
  "Database",
  "Network",
  "Cpu",
  "SiPython",
  "SiJavascript",
  "SiReact",
  "SiNodedotjs",
  "SiGit",
  "SiDocker",
  "SiAws",
  "Server",
  "Cloud",
  "Terminal",
  "FileCode",
]
